### ISSUE TITLE
[offtopic] How should one compare C++ frameworks?

### ISSUE THREAD

**Issue by SamuelMarks** [rbock/sqlpp11#361]
For the database layer, I am currently weighing up [ODB](https://www.codesynthesis.com/products/odb), [Oat++](https://oatpp.io), [SOCI](http://soci.sourceforge.net), [cppdb](http://cppcms.com/sql/cppdb), and [sqlpp11](https://github.com/rbock/sqlpp11) [if sqlpp adds support for `CREATE TABLE`]. Also [drogon](https://github.com/an-tao/drogon) seem to have its own [ORM](https://en.wikipedia.org/wiki/Object%E2%80%93relational_mapping) layer, but with only [PostgreSQL](https://www.postgresql.org) and [MySQL](https://www.mysql.com) support I'm a little worried from a testing and server-less perspective (really would be nice to see support for an embedded database like [SQLite](https://www.sqlite.org)).

For the [REST API](https://en.wikipedia.org/wiki/REST_API) layer I haven't started investigating, although I do remember [actix](https://actix.rs) being dethroned and the [drogon C++ framework taking its place](https://github.com/an-tao/drogon).

---

I am planning to use [LLVM](https://llvm.org) ([clang](https://clang.llvm.org), [libclang](https://clang.llvm.org/doxygen/group__CINDEX.html), [libtooling](https://clang.llvm.org/docs/LibTooling.html)) to synchronise [bidirectionally] [OpenAPI](https://en.wikipedia.org/wiki/OpenAPI_Specification) with C++ code. I've done the same in Python, and WiP for Rust, Swift, Java, Kotlin, and TypeScript.

With my compiler driven approach, I expect people to be able to rapidly produce REST API + db backends with full test and doc coverage, and be able to immediately translate the interfaces across language boundaries (e.g., to frontends, or to rewrite a slow-performing Python backend in C++ or Rust).

Currently focussing on the non-[Turing-complete](https://en.wikipedia.org/wiki/Turing_complete) as aspect of this, translating just the interfaces, tests, docs, defaults, and types.

---

I am writing tools to allow engineers to develop faster, and with higher quality. Will only target one ORM and one REST API layer for C++, at least in the short-term.

So my question is, and I understand that posting here will provide a heavily biased answer, how do I decide between the various C++ frameworks?

Thanks

**Comment by rbock** [comment]
That is a tough question :-)

- Will data structures be fixed at compile time (as in C++ structs)? Or will users be able to add fields at runtime?
- Will the structure of queries be known at compile time (e.g. which columns will be select from which tables)? Or will the structure of queries be determined at runtime?
- Is the database known at compile time? Or should the user be able to configure the database backend at runtime?

sqlpp11 works well if data and query structures and database are known at compile time. It gives you a lot of compile time checks to verify the validity of your query. It has the ability to translate query expressions to the dialect of the database where necessary (or prevent you from attempting to use SQL features that are not supported by the database).

Which databases do you need to support?
sqlpp11 has connector libraries for mysql, postgresql, and sqlite3 (and an experimental connector for odbc).

Which colummn types do you need to support?
Do you want library support for foreign keys?

With respect to creating tables:
As soon as you start creating tables inside your C++ program, you are confronted with the question of updating table structures. What happens if the table for type X is already there? But the struct has changed and now has two more data members? How do you deal with a rollback if the new software version has a bug?

Personally, I separate database management from data management. From my perspective, adding migration paths into the runtime is an unnecessary burden. It is orders of magnitude simpler to separate the concerns.

Hope that helps.

Roland

**Comment by SamuelMarks** [comment]
Thanks @rbock, I'm definitely in the compile-time camp, and need proper primary and foreign key support.

The way my compilers are designed is definitively around schemas, schema migration is current unsolved but I expect to infer it via `git diff`s medium-term.

Happy to use multiple libraries to make this work, but I remember there being issues, e.g., with sqlpp support https://github.com/conan-io/wishlist/issues/8

Although it's 2021 now so maybe all those issues are resolved.

[QxORM](https://www.qxorm.com) has a [pretty clean interface](https://www.qxorm.com/qxorm_en/quick_sample.html), but it does depend on Qt and somewhat Boost…

There must be a clean, independent solution to creating and querying models in C++…

Possibly sqlpp is it (once it has a `create table` layer that is to say…)

**Comment by rbock** [comment]
> and need proper primary and foreign key support.

Can you elaborate on that? Do you need that in the code? How would that look like?

> schema migration is current unsolved but I expect to infer it via git diffs medium-term.

That is exactly my point: You are in script-land anyway. You can (should) handle the database structure outside of your application code :-)

**Comment by SamuelMarks** [comment]
@rbock My main thing is a way of defining the entire OpenAPI spec in code, so that it can be translated back to OpenAPI. And I don't want it just as a string, as that provides no semantic benefit.

I'm already doing OpenAPI↔{Rust,Python,TypeScript,Kotlin,Java,Swift}, so I want to expand this methodology to C++.

**Comment by rbock** [comment]
Type-safety and other compile time checks are the key advantages of sqlpp over most other SQL libraries in C++ :-)

I am not really familiar with OpenAPI, but glancing at the docs, the data-types should be fine. 
I am still not sure what kind of support for foreign keys you need? sqlpp11 is agnostic of primary or foreign keys.

And given your description of schema migration, I maintain that you won't need to create tables in the application code.

Random thought, though: My understanding is that you want to generate some code in LLVM, too?  Depending on the extent of that, you might not need type-safety in the underlying database layer?

**Comment by SamuelMarks** [comment]
@rbock No no, just using the LLVM toolchain to walk the AST—and maybe some other trees—to extract/manipulate specific things: routes, models, docs, and tests.

PK/FK relationships are important, because if I auto-rewrite the C++ code in Rust, Python, or TypeScript then each of those other interfaces [specific frameworks therein] are more traditional ORMs, that general the DDL stuff (`CREATE TABLE`, `CREATE INDEX`, &etc.). So I want something orthogonal in C++, otherwise I can't make sweeping statements/claims like OpenAPI↔{Rust,Python,TypeScript,Kotlin,Java,Swift,**C++**}

**Comment by rbock** [comment]
There are no dedicated functions for `CREATE TABLE` and other SQL statements to modify the table structure.

However, you can use the `execute` function of the `connection` classes to send arbitrary strings to the database. If I wanted to create tables in my application code, I would use those (and actually, that's how the examples for sqlite3 work).
